version: '2'
services:
    moba-app:
        image: moba
        external_links:
            - moba-mongodb:mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=moba
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    moba-mongodb:
        extends:
            file: mongodb.yml
            service: moba-mongodb
