version: '2'
services:
    moba-mongodb:
        container_name: moba-mongodb
        image: mongo:3.3.5
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/moba/mongodb/:/data/db/
