version: '2'
services:
    moba-mongodb:
        container_name: moba-mongodb
        image: mongo:3.3.5
        ports:
            - "27017:27017"
        command: mongos --configdb moba-mongodb-config
    moba-mongodb-node:
        build:
            context: .
            dockerfile: mongodb/MongoDB.Dockerfile
        command: mongod --replSet rs1 --noprealloc --smallfiles
    moba-mongodb-config:
        image: mongo:3.3.5
        container_name: moba-mongodb-config
        command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
